# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://daltonmenezes.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: ".Dalton Menezes"
  #avatar: avatar.jpg
  gravatar: 43f6793db9348cfb8e692608cca69540
  description: "cyber daydreams, coded insults and silicon metaphorical orgasms" # used by search engines

  # Header and footer text
  # header_text: >
     #<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

    # <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  #header_text_feature_image: "img/background.jpg"
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a> and customized by me

  # Icons
  rss: true
  facebook: https://www.facebook.com/dalton.menezes.oficial
  github: "daltonmenezes"
  google_plus:
  instagram:
  linkedin: https://linkedin.com/in/daltonmenezes # Full URL
  twitter: "daltonmenezes"
  email_address: daltonmenezes@outlook.com # Full email address, e.g. "sam@example.com"
  youtube:

  # Scripts
  google_analytics: UA-77452250-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: daltonmenezes
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 10
paginate_path: "page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
